### ISSUE TITLE
 ERR: http request returned status 400 BAD REQUEST

### ISSUE THREAD

**Issue by chase-qi** [bwalex/tftp-http-proxy#2]
With master branch commit 0c5ac2b65f319f3894bf2dbae97f3d8f389bb07d, and the following usage:
/opt/tftp-http-proxy/dist/tftp-http-proxy  -http-base-url "http://localhost:5000/tftp"

tftp request returns the below error:

Oct 31 18:40:26 mr-provisioner tftp-http-proxy[476]: 2017/10/31 18:40:26 INFO: New TFTP request (test) from 192.0.2.102
Oct 31 18:40:26 mr-provisioner tftp-http-proxy[476]: 2017/10/31 18:40:26 ERR: http request returned status 400 BAD REQUEST

With the initial commit aa13e2d7e15c527ddd6eafc55c82b3df747ec947, and the follow usage:

/opt/tftp-http-proxy/dist/tftp-http-proxy -http-base-url=http://127.0.0.1:5000/tftp -http-append-path=false

tftp service works well.

**Comment by bwalex** [comment]
I fail to see how this is a bug in tftp-http-proxy. If the backend that you are using returns a 400, then, clearly, tftp-http-proxy is also going to fail. Are you saying there's something wrong with the request tftp-http-proxy makes, such as any missing headers?

**Comment by bwalex** [comment]
I've looked into it, and there's nothing wrong with the code. You are probably being bitten by the fact that, on a 301 HTTP redirect, golang's http library does not send the headers again. You can either avoid the redirect in the first place (by using the correct url to http-base-url, e.g. `http://127.0.0.1:5000/tftp/` (note the trailing slash)) or by compiling with go >= 1.8.

For good measure, and to avoid confusion in the future, I've recompiled the release version (under github's release tab) with go 1.9 - that should now follow redirects as expected.

**Comment by chase-qi** [comment]
I am running mr-provisioner on debian9 with golang-1.7, this matches the version issue you mentioned above. And yes, I validated that it works with the trailing slash. Thanks for looking into it!
