### ISSUE TITLE
Not listening on IPv4 by default

### ISSUE THREAD

**Issue by niedbalski** [bwalex/tftp-http-proxy#3]
By default tftp-http-proxy doesn't binds on udp4 just on udp6 (when using :69 as addr).

niedbalski@theos-mobile:~/sources/go/github.com/niedbalski/tftp-http-proxy$ sudo lsof -p $(pgrep tftp) | grep -i udp
tftp-http 23063 root    3u     IPv6 1322723      0t0      UDP *:tftp

**Comment by bwalex** [comment]
To be clear, this isn't really an issue as Linux (and most other systems) use IPv4-mapped IPv6 - so even though lsof/netstat/etc only show IPv6, it is actually listening on both (see for example: https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses)

**Comment by niedbalski** [comment]
Well,

That's not really happening, isn't listening on IPv4 :69 by default (tested before raising this ticket).

niedbalski@theos-mobile:~/sources/go/github.com/niedbalski/tftp-http-proxy$ sudo lsof -p $(pgrep tftp) | grep -i udp
tftp-http 23063 root 3u IPv6 1322723 0t0 UDP *:tftp

The machine isn't able to serve tftp requests by default (Ubuntu Xenial, kernel 4.14)

**Comment by bwalex** [comment]
As I said, that lsof means nothing, due to IPv4-mapped IPv6. It'll show an IPv6 binding that actually also gets IPv4 packets. Unless, of course, you have set the `net.ipv6.bindv6only` sysctl to 1 (but it defaults to 0 on every system I've ever seen).

If in doubt, please read `man 7 ipv6`.

**Comment by niedbalski** [comment]
OK, in practice isn't listening on IPv4 (kernel 4.14) , so either the documentation is not accurate or some other setting in the system is altering the documented behavior.
